"""Pydantic schemas for Written Narrative."""

from typing import List, Optional
from pydantic import BaseModel, Field
from storyteller.schemas.story_plan import StoryShape


class PrescriptiveAction(BaseModel):
    action_item: str = Field(description="Actionable strategic recommendation")
    supporting_fact_ids: List[str] = Field(description="Fact IDs motivating this recommendation")
    hypothesis: str = Field(description="Expected business hypothesis / rationale")
    suggested_validation: str = Field(description="Suggested check or experiment to validate before full rollout")


class NarrativePage(BaseModel):
    page_number: int = Field(ge=1, description="Page index")
    action_title: str = Field(description="Action-oriented title stating the insight")
    headline_banner: str = Field(description="Highlight callout text with fact placeholders")
    body_text: str = Field(description="Paragraph explanation with fact placeholders, e.g. {F012.value:pct}")
    bullet_insights: List[str] = Field(default_factory=list, description="List of bulleted observations with citations")
    actions: List[PrescriptiveAction] = Field(default_factory=list, description="Prescriptive action items (if Act 4)")
    cited_fact_ids: List[str] = Field(description="All fact IDs cited anywhere on this page")


class Narrative(BaseModel):
    report_title: str = Field(description="Overall executive report title")
    story_shape: StoryShape = Field(description="Story shape used")
    pages: List[NarrativePage] = Field(description="Complete narrative text by page")
    is_fallback_template: bool = Field(default=False, description="True if generated by deterministic fallback")
